-- AlterTable
ALTER TABLE "SiteTheme" ADD COLUMN     "brushHue" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "brushOpacity" INTEGER NOT NULL DEFAULT 75,
ADD COLUMN     "brushSaturate" INTEGER NOT NULL DEFAULT 100;
